CREATE TYPE role AS ENUM ('user', 'admin');
CREATE TABLE IF NOT EXISTS users(
    email VARCHAR(50) NOT NULL PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    intro VARCHAR(256) NULL DEFAULT NULL,
    profile VARCHAR(256) NULL DEFAULT NULL,
    role role NOT NULL DEFAULT 'user',
    password_hash VARCHAR(256) NOT NULL,
    registered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);